const fs=require('fs');
const vm=require('vm');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(x=>x[1]);
const store=new Map(),listeners=new Map(),elements=new Map();
function classList(){const s=new Set();return{add:(...x)=>x.forEach(v=>s.add(v)),remove:(...x)=>x.forEach(v=>s.delete(v)),toggle:(x,v)=>v===undefined?(s.has(x)?(s.delete(x),false):(s.add(x),true)):(v?(s.add(x),true):(s.delete(x),false)),contains:x=>s.has(x)}}
const ctx2d=new Proxy({createLinearGradient:()=>({addColorStop(){}}),measureText:t=>({width:String(t).length*7}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:{width:390,height:844}}, {get:(o,k)=>k in o?o[k]:(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
function element(id=''){if(elements.has(id))return elements.get(id);const e={id,dataset:{},style:{},classList:classList(),children:[],textContent:'',innerHTML:'',value:'',width:id==='canvas'?390:100,height:id==='canvas'?844:100,disabled:false,appendChild(x){this.children.push(x);return x},remove(){this.removed=true},addEventListener(t,fn){(this._events||(this._events={}))[t]=fn},removeEventListener(){},setAttribute(){},focus(){},blur(){},click(){this.onclick?.({preventDefault(){},stopPropagation(){},target:this})},closest(){return this},contains(){return true},getContext:()=>ctx2d,getBoundingClientRect:()=>({left:8,top:8,right:70,bottom:70,width:62,height:62}),setPointerCapture(){},querySelector:()=>element(id+':q'),querySelectorAll:()=>[],offsetWidth:10};elements.set(id,e);return e}
const document={
 documentElement:element('html'),body:element('body'),hidden:false,visibilityState:'visible',
 getElementById:id=>element(id),createElement:t=>element('created-'+t+'-'+elements.size),
 querySelector:q=>element('query-'+q),querySelectorAll:q=>q==='.tab'?[]:[element('queryall-'+q)],
 addEventListener(t,fn){listeners.set('document:'+t,fn)}
};
document.documentElement.innerHTML=html;
function AudioStub(){const node=()=>({gain:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},frequency:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},Q:{value:0},connect(){return this},start(){},stop(){},type:''});this.currentTime=0;this.sampleRate=44100;this.destination=node();this.createGain=node;this.createOscillator=node;this.createBiquadFilter=node;this.createBuffer=()=>({getChannelData:()=>new Float32Array(4410)});this.createBufferSource=node;this.resume=()=>Promise.resolve()}
const sandbox={console,document,innerWidth:390,innerHeight:844,devicePixelRatio:1,location:{reload(){}},navigator:{vibrate(){}},localStorage:{getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},performance:{now:(()=>{let n=1000;return()=>n+=16})()},crypto:require('crypto').webcrypto,requestAnimationFrame(){},cancelAnimationFrame(){},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},addEventListener(t,fn){listeners.set('window:'+t,fn)},removeEventListener(){},getComputedStyle:()=>({getPropertyValue:()=>'',display:'block'}),visualViewport:null,AudioContext:AudioStub,webkitAudioContext:AudioStub,URL,Math,Date,JSON,Array,Object,Number,String,Boolean,Set,Map,WeakMap,Uint8ClampedArray,BigInt,Infinity,NaN};
sandbox.window=sandbox;sandbox.globalThis=sandbox;
const context=vm.createContext(sandbox);
const results=[];
function check(name,fn){try{const value=fn();results.push({name,pass:value!==false,detail:value===true||value===undefined?'OK':String(value)})}catch(e){results.push({name,pass:false,detail:e.stack||e.message})}}
for(let i=0;i<scripts.length;i++)check('script '+(i+1)+' evaluates',()=>{vm.runInContext(scripts[i],context,{filename:'index.html#script-'+(i+1)});return true});
function run(code){return vm.runInContext(code,context)}
check('full system gate',()=>run('SYSTEM_GATE.run() && SYSTEM_GATE.results.length===23'));
check('legacy smoke gate',()=>run(`SMOKE_GATE.run();let f=SMOKE_GATE.results.filter(x=>!x.pass).map(x=>x.name).filter(x=>x!=='attack action path');f.length?f.join(', '):true`));
check('enemy click mounts no floating target panel',()=>!html.includes("target.id='rpgTargetPanel'")&&!html.includes('id="rpgTargetPanel"'));
check('QA checklist closes and reopens',()=>run(`(()=>{setSmokePanelOpen(false,false);let p=document.getElementById('smokePanel'),t=document.getElementById('smokePanelToggle'),closed=p.dataset.dismissed==='true'&&t.dataset.visible==='true';setSmokePanelOpen(true,false);let opened=p.dataset.dismissed==='false'&&p.dataset.forceOpen==='true'&&t.dataset.visible==='false';return closed&&opened})()`));
check('player is smaller and NPCs are larger',()=>run('CHARACTER_SCALE.player<1&&CHARACTER_SCALE.npc>1&&CHARACTER_SCALE.npcHitRadius>=1'));
check('combat callout helper is available',()=>run("typeof tacticalCallout==='function'"));
check('world update and render',()=>run('update(.016);draw();true'));
check('NPC A-star returns route',()=>run('NPC_ROUTER.plan(70,54,{x:61,y:48}).length>0'));
check('all NPCs have identity and trade',()=>run('state.npcs.every(n=>SETTLEMENT_PRESENTATION.profiles[n.name]&&SETTLEMENT_PRESENTATION.trades[n.name]?.length===2)'));
check('trade buy is atomic',()=>run(`(()=>{let c=state.player.coins,v=state.settlement.goods;state.player.coins=100;let r=NPC_TRADE.transact('Bram','goods','buy'),ok=r.ok&&state.player.coins===85&&state.settlement.goods===v+2;state.player.coins=c;state.settlement.goods=v;return ok})()`));
check('trade rejects insufficient funds without mutation',()=>run(`(()=>{let c=state.player.coins,v=state.settlement.goods;state.player.coins=0;let r=NPC_TRADE.transact('Bram','goods','buy'),ok=!r.ok&&state.player.coins===0&&state.settlement.goods===v;state.player.coins=c;return ok})()`));
check('item equip transaction preserves unique IDs',()=>run(`(()=>{let snap=durableState(),it=ITEM_LEDGER.acquire(rollItem(1,'head'),'test'),r=ITEM_LEDGER.equipId(it.id),ids=[...state.inventory,...Object.values(state.equipped).filter(Boolean)].map(x=>x.id),ok=!!r&&ids.length===new Set(ids).size;applySave(snap);return ok})()`));
check('progression level-up awards skill point',()=>run(`(()=>{let snap=durableState(),l=state.player.level,sp=state.player.skillPoints;PROGRESSION_CORE.grantXp(PROGRESSION_CORE.xpNeed(l),'test');let ok=state.player.level===l+1&&state.player.skillPoints===sp+1;applySave(snap);return ok})()`));
check('checksum save commit verifies',()=>run('SAVE_SYSTEM.commit(false)&&SAVE_SYSTEM.unpack(storageGet(SAVE_PRIMARY)).revision>=1'));
check('corrupt primary recovers from verified slot',()=>run(`(()=>{let good=storageGet(SAVE_PRIMARY);storageSet(SAVE_PRIMARY,'corrupt');let r=readSaveRecord(),ok=!!r&&validateSave(r.data);storageSet(SAVE_PRIMARY,good);return ok})()`));
check('cutaway modes cycle',()=>run(`(()=>{let m=SETTLEMENT_PRESENTATION.roofMode;cycleRoofMode();let ok=SETTLEMENT_PRESENTATION.roofMode!==m;SETTLEMENT_PRESENTATION.roofMode=m;return ok})()`));
check('dungeon enter/leave callable',()=>run(`(()=>{let snap=durableState();state.dungeonUnlocked=true;state.adventure.unlocks.rootVault=true;enterRootVault();let a=state.mode==='dungeon';leaveRootVault();let b=state.mode==='world';applySave(snap);return a&&b})()`));
check('atmosphere quality budgets are capped',()=>run(`(()=>{let old=state.presentation.atmosphere,q=PERF.quality;state.presentation.atmosphere='FULL';PERF.quality='FULL';let a=ATMOSPHERE_SYSTEM.budget()===16;PERF.quality='LOW';let b=ATMOSPHERE_SYSTEM.budget()===4;state.presentation.atmosphere=old;PERF.quality=q;return a&&b})()`));
check('atmosphere setting survives save restore',()=>run(`(()=>{let old=state.presentation.atmosphere;state.presentation.atmosphere='BALANCED';let s=durableState();state.presentation.atmosphere='LOW';let ok=applySave(s)&&state.presentation.atmosphere==='BALANCED';state.presentation.atmosphere=old;return ok})()`));
check('equipped family owns combat profile',()=>run(`(()=>{let old=state.equipped.weapon;state.equipped.weapon={id:'qa-axe',name:'QA Axe',baseType:'axe',type:'weapon',rarity:'Common'};let ok=weaponType()==='axe'&&COMBAT_CORE.weapon()==='axe'&&COMBAT_CORE.profile()===COMBAT_CORE.ids.axe;state.equipped.weapon=old;return ok})()`));
check('ranged attack spawns authored projectile',()=>run(`(()=>{let oldW=state.equipped.weapon,oldE=state.enemies,oldP=state.combat.projectiles;state.equipped.weapon={id:'qa-bow',name:'QA Bow',baseType:'bow',type:'weapon',rarity:'Common'};state.enemies=[{x:state.player.x+3,y:state.player.y,type:'Bandit',hp:40,maxHp:40,dead:false}];state.combat.projectiles=[];COMBAT_CORE.current={profile:COMBAT_CORE.ids.bow};COMBAT_CORE.hitSet.clear();COMBAT_CORE.executeAttack();let ok=state.combat.projectiles.length===1&&state.combat.projectiles[0].kind==='arrow';state.equipped.weapon=oldW;state.enemies=oldE;state.combat.projectiles=oldP;COMBAT_CORE.current=null;return ok})()`));
check('melee family creates authored slash and damage',()=>run(`(()=>{let oldW=state.equipped.weapon,oldE=state.enemies,oldS=state.combat.slashes;state.equipped.weapon={id:'qa-axe',name:'QA Axe',baseType:'axe',type:'weapon',rarity:'Common'};let enemy={x:state.player.x+1.4,y:state.player.y,type:'Bandit',kind:'normal',hp:80,maxHp:80,atk:1,dead:false};state.enemies=[enemy];state.combat.slashes=[];COMBAT_CORE.current={profile:COMBAT_CORE.ids.axe};COMBAT_CORE.hitSet.clear();COMBAT_CORE.executeAttack();let ok=enemy.hp<80&&state.combat.slashes.some(s=>s.family==='axe');state.equipped.weapon=oldW;state.enemies=oldE;state.combat.slashes=oldS;COMBAT_CORE.current=null;return ok})()`));
check('all weapon poses are finite',()=>run(`['sword','axe','spear','dagger','bow','staff','wand','hammer','scythe'].every(w=>['windup','active','recovery'].every(p=>Number.isFinite(COMBAT_PRESENTATION.pose(w,p,0).angle)))`));
check('dungeon generation deterministic by seed',()=>run(`(()=>{let snap=durableState();DUNGEON_RUN.generate(771337);let a=DUNGEON_RUN.fingerprint(),va=DUNGEON_RUN.validate();DUNGEON_RUN.generate(771337);let b=DUNGEON_RUN.fingerprint(),vb=DUNGEON_RUN.validate();applySave(snap);return va.ok&&vb.ok&&a===b})()`));
check('all dungeon variants have valid entry checkpoints',()=>run(`(()=>{let snap=durableState(),old=state.player.level,ok=true;for(let seed=77000;seed<77120;seed++){DUNGEON_RUN.generate(seed);ok=ok&&DUNGEON_RUN.validate().ok&&dungeonTile(state.dungeon.entrance.x,state.dungeon.entrance.y)==='floor'}state.player.level=old;applySave(snap);return ok})()`));
check('reliquary branch grants bonus chest',()=>run(`(()=>{let snap=durableState(),found=false,ok=false;state.player.level=7;for(let seed=1;seed<800&&!found;seed++){DUNGEON_RUN.generate(seed);if(state.dungeon.run.branch==='reliquary'){found=true;ok=state.dungeon.chests.length===4&&DUNGEON_RUN.validate().ok}}applySave(snap);return found&&ok})()`));
const failed=results.filter(x=>!x.pass);
console.log(JSON.stringify({summary:{passed:results.length-failed.length,total:results.length,failed:failed.length},results},null,2));
process.exitCode=failed.length?1:0;
